[workspace]
members = [
    "citadel-workspace-server-kernel",
    "citadel-workspace-internal-service",
]
resolver = "2"

[workspace.dependencies]
structopt = { version = "0.3.26" }
tokio = { version = "1.28.1", features = ["full"] }
citadel-internal-service = { git = "https://github.com/Avarok-Cybersecurity/citadel-internal-service/", branch = "reliable-ordered-message-protocol" }
citadel_sdk = { git = "https://github.com/Avarok-Cybersecurity/Citadel-Protocol/" }
citadel_types = { git = "https://github.com/Avarok-Cybersecurity/Citadel-Protocol/" }
citadel_logging = { git = "https://github.com/Avarok-Cybersecurity/Citadel-Protocol/" }
parking_lot = { version = "0.12", features = ["send_guard"] }
lazy_static = { version = "1.4.0" }
