[package]
name = "citadel_workspace_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# localhost-testing = ["citadel_sdk/localhost-testing"]
# vendored = ["citadel-internal-service/vendored"]

[[bin]]
name = "citadel_workspace_server"
path = "src/main.rs"

[dependencies]
structopt = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
citadel-internal-service = { workspace = true }
citadel_sdk = { workspace = true }
citadel_types = { workspace = true }
citadel_logging = { workspace = true }
parking_lot = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { workspace = true, features = ["v4"] }
async-trait = "0.1.88"
rstest = "0.25.0"
futures = "0.3.31"

[dev-dependencies]
citadel_sdk = { workspace = true, features = ["localhost-testing"] }
citadel-internal-service-test-common = { workspace = true }
citadel-internal-service-types = { workspace = true }
citadel-internal-service-connector = { workspace = true }